/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import Persistencia.IncluirEditarDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import Objetos.Veiculo;
import javax.swing.JOptionPane;

/**
 *
 * @author Pedrinho
 */
public class CadastroVeiculo extends javax.swing.JFrame {

    /**
     * Creates new form CadastroCliente
     */
    public CadastroVeiculo() {
        initComponents();
        tab_cadastro.setEnabled(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tab_cadastro = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        l_cadCliNome = new javax.swing.JLabel();
        c_modelo = new javax.swing.JTextField();
        l_cadCLiDataNasc = new javax.swing.JLabel();
        l_cadCliRg = new javax.swing.JLabel();
        c_cor = new javax.swing.JTextField();
        l_cadCliCpf = new javax.swing.JLabel();
        c_placa = new javax.swing.JTextField();
        l_telefone = new javax.swing.JLabel();
        c_renavam = new javax.swing.JFormattedTextField();
        c_ano = new javax.swing.JFormattedTextField();
        l_cadCliCpf1 = new javax.swing.JLabel();
        c_chassi = new javax.swing.JTextField();
        l_telefone1 = new javax.swing.JLabel();
        cbx_tipo = new javax.swing.JComboBox<>();
        bt_sair = new javax.swing.JButton();
        bt_salvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Cadastro Veículo");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(140, 0, 120, 20);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(null);

        l_cadCliNome.setText("Marca \\ Modelo \\ Versão");
        jPanel2.add(l_cadCliNome);
        l_cadCliNome.setBounds(20, 190, 160, 30);
        jPanel2.add(c_modelo);
        c_modelo.setBounds(20, 220, 200, 30);

        l_cadCLiDataNasc.setText("Ano modelo");
        jPanel2.add(l_cadCLiDataNasc);
        l_cadCLiDataNasc.setBounds(20, 70, 80, 30);

        l_cadCliRg.setText("Renavam");
        jPanel2.add(l_cadCliRg);
        l_cadCliRg.setBounds(20, 10, 90, 30);
        jPanel2.add(c_cor);
        c_cor.setBounds(20, 160, 140, 30);

        l_cadCliCpf.setText("Placa");
        jPanel2.add(l_cadCliCpf);
        l_cadCliCpf.setBounds(240, 10, 60, 30);
        jPanel2.add(c_placa);
        c_placa.setBounds(240, 40, 130, 30);

        l_telefone.setText("Cor");
        jPanel2.add(l_telefone);
        l_telefone.setBounds(20, 130, 50, 30);

        c_renavam.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###########"))));
        jPanel2.add(c_renavam);
        c_renavam.setBounds(20, 40, 190, 30);

        try {
            c_ano.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(c_ano);
        c_ano.setBounds(20, 100, 150, 30);

        l_cadCliCpf1.setText("Chassi");
        jPanel2.add(l_cadCliCpf1);
        l_cadCliCpf1.setBounds(190, 70, 60, 30);
        jPanel2.add(c_chassi);
        c_chassi.setBounds(190, 100, 180, 30);

        l_telefone1.setText("Espécie");
        jPanel2.add(l_telefone1);
        l_telefone1.setBounds(190, 130, 50, 30);

        cbx_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carro", "Moto", "Ônibus" }));
        jPanel2.add(cbx_tipo);
        cbx_tipo.setBounds(190, 160, 130, 30);

        bt_sair.setText("Sair");
        bt_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_sairActionPerformed(evt);
            }
        });
        jPanel2.add(bt_sair);
        bt_sair.setBounds(300, 310, 80, 30);

        bt_salvar.setText("Salvar");
        bt_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salvarActionPerformed(evt);
            }
        });
        jPanel2.add(bt_salvar);
        bt_salvar.setBounds(210, 310, 80, 30);

        tab_cadastro.addTab("Veiculo", jPanel2);

        jPanel1.add(tab_cadastro);
        tab_cadastro.setBounds(0, 20, 400, 390);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salvarActionPerformed
        // TODO add your handling code here:
        if (!verificaVazio()) {
            IncluirEditarDAO iedao = new IncluirEditarDAO();

            try {
                iedao.Incluir(preencherVeiculo());

            } catch (SQLException ex) {
                Logger.getLogger(CadastroVeiculo.class.getName()).log(Level.SEVERE, null, ex);
            }

            JOptionPane.showMessageDialog(null, "Salvo com sucesso!");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos para proseguir ");
        }

    }//GEN-LAST:event_bt_salvarActionPerformed

    private void bt_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_sairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_bt_sairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>
        java.awt.EventQueue.invokeLater(() -> {
            new CadastroVeiculo().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_sair;
    private javax.swing.JButton bt_salvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.JFormattedTextField c_ano;
    private javax.swing.JTextField c_chassi;
    private javax.swing.JTextField c_cor;
    private javax.swing.JTextField c_modelo;
    private javax.swing.JTextField c_placa;
    private javax.swing.JFormattedTextField c_renavam;
    private javax.swing.JComboBox<String> cbx_tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel l_cadCLiDataNasc;
    private javax.swing.JLabel l_cadCliCpf;
    private javax.swing.JLabel l_cadCliCpf1;
    private javax.swing.JLabel l_cadCliNome;
    private javax.swing.JLabel l_cadCliRg;
    private javax.swing.JLabel l_telefone;
    private javax.swing.JLabel l_telefone1;
    private javax.swing.JTabbedPane tab_cadastro;
    // End of variables declaration//GEN-END:variables

    public Veiculo preencherVeiculo() {
        Veiculo obj = new Veiculo();

        obj.setModelo(c_modelo.getText());
        obj.setPlaca(c_placa.getText());
        obj.setTipo((String) cbx_tipo.getSelectedItem());
        obj.setRenavam(c_renavam.getText());
        String ano = c_ano.getText();
        obj.setAno(Integer.parseInt(ano));
        obj.setValidade();
        obj.setCor(c_cor.getText());
        obj.setChassi(c_chassi.getText());
        return obj;
    }

    public boolean verificaVazio() {
        return (c_placa.getText().equals("") || c_chassi.getText().equals("")
                || c_renavam.getText().equals("") || c_ano.getText().equals("")
                || c_cor.getText().equals("") || c_modelo.getText().equals(""));
    }
}
