/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import Persistencia.IncluirEditarDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import Objetos.ClienteCnh;
import javax.swing.JOptionPane;

/**
 *
 * @author Pedrinho
 */
public class CadastroClienteCNH extends javax.swing.JFrame {

    /**
     * Creates new form CadastroCliente
     */
    public CadastroClienteCNH() {
        initComponents();
        this.setLocationRelativeTo(null);
        tab_cadastro.setEnabled(false);
        bt_salvar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tab_cadastro = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        l_cadCliNome = new javax.swing.JLabel();
        c_nome = new javax.swing.JTextField();
        l_cadCLiDataNasc = new javax.swing.JLabel();
        l_cadCliRg = new javax.swing.JLabel();
        c_rg = new javax.swing.JTextField();
        l_cadCliCpf = new javax.swing.JLabel();
        l_telefone = new javax.swing.JLabel();
        c_celular = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        c_endRua = new javax.swing.JTextField();
        c_endBairro = new javax.swing.JTextField();
        c_endNum = new javax.swing.JTextField();
        c_endComp = new javax.swing.JTextField();
        l_cadCliEnd2 = new javax.swing.JLabel();
        l_cadCliEnd4 = new javax.swing.JLabel();
        l_cadCliEnd5 = new javax.swing.JLabel();
        l_cadCliEnd6 = new javax.swing.JLabel();
        l_cadCliEnd7 = new javax.swing.JLabel();
        c_endCep = new javax.swing.JFormattedTextField();
        l_cadCliEnd3 = new javax.swing.JLabel();
        dt_dataNasc = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        r_feminino = new javax.swing.JRadioButton();
        r_masculino = new javax.swing.JRadioButton();
        c_cpf = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        cbx_catPretendida = new javax.swing.JComboBox<>();
        l_cadCliEnd1 = new javax.swing.JLabel();
        c_orcamento = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbx_formaPagamento = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        bt_proximo = new javax.swing.JButton();
        bt_anterior = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        bt_salvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Cadastro Cliente");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 0, 110, 20);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setLayout(null);

        l_cadCliNome.setText("Nome");
        jPanel2.add(l_cadCliNome);
        l_cadCliNome.setBounds(40, 10, 70, 30);
        jPanel2.add(c_nome);
        c_nome.setBounds(40, 40, 170, 30);

        l_cadCLiDataNasc.setText("Data de Nasc.");
        jPanel2.add(l_cadCLiDataNasc);
        l_cadCLiDataNasc.setBounds(220, 10, 80, 30);

        l_cadCliRg.setText("RG");
        jPanel2.add(l_cadCliRg);
        l_cadCliRg.setBounds(40, 70, 40, 30);
        jPanel2.add(c_rg);
        c_rg.setBounds(40, 100, 140, 30);

        l_cadCliCpf.setText("CPF");
        jPanel2.add(l_cadCliCpf);
        l_cadCliCpf.setBounds(220, 70, 40, 30);

        l_telefone.setText("Celular");
        jPanel2.add(l_telefone);
        l_telefone.setBounds(40, 130, 50, 30);

        try {
            c_celular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(c_celular);
        c_celular.setBounds(40, 160, 110, 30);

        jPanel3.setLayout(null);

        c_endRua.setToolTipText("");
        jPanel3.add(c_endRua);
        c_endRua.setBounds(10, 30, 190, 30);
        jPanel3.add(c_endBairro);
        c_endBairro.setBounds(270, 30, 130, 30);
        jPanel3.add(c_endNum);
        c_endNum.setBounds(210, 30, 50, 30);

        c_endComp.setText("CASA");
        jPanel3.add(c_endComp);
        c_endComp.setBounds(10, 90, 190, 30);

        l_cadCliEnd2.setText("Bairro");
        jPanel3.add(l_cadCliEnd2);
        l_cadCliEnd2.setBounds(270, 10, 50, 16);

        l_cadCliEnd4.setText("Rua");
        jPanel3.add(l_cadCliEnd4);
        l_cadCliEnd4.setBounds(10, 10, 70, 16);

        l_cadCliEnd5.setText("Complemento");
        jPanel3.add(l_cadCliEnd5);
        l_cadCliEnd5.setBounds(10, 70, 90, 16);

        l_cadCliEnd6.setText("Num");
        jPanel3.add(l_cadCliEnd6);
        l_cadCliEnd6.setBounds(210, 10, 50, 16);

        l_cadCliEnd7.setText("CEP");
        jPanel3.add(l_cadCliEnd7);
        l_cadCliEnd7.setBounds(210, 60, 50, 30);

        try {
            c_endCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        c_endCep.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jPanel3.add(c_endCep);
        c_endCep.setBounds(210, 90, 120, 30);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(40, 230, 420, 130);

        l_cadCliEnd3.setText("Endereco");
        jPanel2.add(l_cadCliEnd3);
        l_cadCliEnd3.setBounds(40, 200, 70, 30);

        dt_dataNasc.setDateFormatString("dd/MM/y");
        dt_dataNasc.setMaxSelectableDate(new java.util.Date(7289578800000L));
        dt_dataNasc.setMinSelectableDate(new java.util.Date(-2208977612000L));
        jPanel2.add(dt_dataNasc);
        dt_dataNasc.setBounds(220, 40, 130, 30);

        jLabel4.setText("Sexo");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(220, 130, 50, 30);

        buttonGroup3.add(r_feminino);
        r_feminino.setSelected(true);
        r_feminino.setText("Feminino");
        jPanel2.add(r_feminino);
        r_feminino.setBounds(220, 160, 100, 21);

        buttonGroup3.add(r_masculino);
        r_masculino.setText("Masculino");
        jPanel2.add(r_masculino);
        r_masculino.setBounds(220, 180, 110, 21);

        try {
            c_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        c_cpf.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jPanel2.add(c_cpf);
        c_cpf.setBounds(220, 100, 140, 30);

        tab_cadastro.addTab("Dados Pessoais", jPanel2);

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));
        jPanel4.setLayout(null);

        cbx_catPretendida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Moto inicial", "Moto adição", "Carro inicial", "Carro adição", "Carro e Moto", "Ônibus" }));
        cbx_catPretendida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_catPretendidaActionPerformed(evt);
            }
        });
        jPanel4.add(cbx_catPretendida);
        cbx_catPretendida.setBounds(40, 40, 200, 30);

        l_cadCliEnd1.setText("Categoria pretendida");
        jPanel4.add(l_cadCliEnd1);
        l_cadCliEnd1.setBounds(40, 20, 111, 16);

        c_orcamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0.##"))));
        c_orcamento.setEnabled(false);
        c_orcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_orcamentoActionPerformed(evt);
            }
        });
        jPanel4.add(c_orcamento);
        c_orcamento.setBounds(40, 150, 130, 30);

        jLabel2.setText("Orçamento");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(40, 130, 70, 16);

        jLabel3.setText("Forma de Pagamento");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(280, 20, 130, 16);

        cbx_formaPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "À Vista", "2x Cartão", "3x Cartão", "4x Cartão" }));
        jPanel4.add(cbx_formaPagamento);
        cbx_formaPagamento.setBounds(280, 40, 160, 30);

        tab_cadastro.addTab("CNH", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 379, Short.MAX_VALUE)
        );

        tab_cadastro.addTab("Curso", jPanel5);

        jPanel1.add(tab_cadastro);
        tab_cadastro.setBounds(0, 20, 540, 410);

        bt_proximo.setText("Próximo");
        bt_proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_proximoActionPerformed(evt);
            }
        });
        jPanel1.add(bt_proximo);
        bt_proximo.setBounds(220, 440, 80, 30);

        bt_anterior.setText("Anterior");
        bt_anterior.setEnabled(false);
        bt_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_anteriorActionPerformed(evt);
            }
        });
        jPanel1.add(bt_anterior);
        bt_anterior.setBounds(120, 440, 90, 30);

        jButton1.setText("Sair");
        jButton1.setToolTipText("Limpar Formulário");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(440, 440, 80, 30);

        bt_salvar.setText("Salvar");
        bt_salvar.setEnabled(false);
        bt_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salvarActionPerformed(evt);
            }
        });
        jPanel1.add(bt_salvar);
        bt_salvar.setBounds(20, 440, 80, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_anteriorActionPerformed
        // TODO add your handling code here:

        tab_cadastro.setSelectedIndex(0);
        bt_proximo.setEnabled(true);
        bt_anterior.setEnabled(false);
        bt_salvar.setEnabled(false);

    }//GEN-LAST:event_bt_anteriorActionPerformed

    private void bt_proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_proximoActionPerformed
        // TODO add your handling code here:
        if (verificaVazio()) {
            JOptionPane.showMessageDialog(null, "Preencha todos campos para prosseguir!", "Atenção", 0);
        } else {
            tab_cadastro.setSelectedIndex(1);
            bt_salvar.setEnabled(true);
            bt_anterior.setEnabled(true);
            bt_proximo.setEnabled(false);
        }
    }//GEN-LAST:event_bt_proximoActionPerformed

    private void cbx_catPretendidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_catPretendidaActionPerformed
        // TODO add your handling code here:7
        String aux = (String) cbx_catPretendida.getSelectedItem();
        switch (aux) {
            case "Moto inicial" ->
                c_orcamento.setText("1200,00");
            case "Moto adição" ->
                c_orcamento.setText("1000,00");
            case "Carro inicial" ->
                c_orcamento.setText("1400,00");
            case "Carro adição" ->
                c_orcamento.setText("1200,00");
            case "Carro e Moto" ->
                c_orcamento.setText("2400,00");
            case "Ônibus" ->
                c_orcamento.setText("1500,00");
            default -> {
            }
        }
    }//GEN-LAST:event_cbx_catPretendidaActionPerformed

    private void bt_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salvarActionPerformed
        // TODO add your handling code here:
        IncluirEditarDAO iedao = new IncluirEditarDAO();
        preencherCliente();

        try {
            iedao.Incluir(obj);

        } catch (SQLException ex) {
            Logger.getLogger(CadastroClienteCNH.class.getName()).log(Level.SEVERE, null, ex);
        }

        JOptionPane.showMessageDialog(null, "Salvo com sucesso!");
        this.dispose();

    }//GEN-LAST:event_bt_salvarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void c_orcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_orcamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_orcamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CadastroClienteCNH().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_anterior;
    private javax.swing.JButton bt_proximo;
    private javax.swing.JButton bt_salvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.JFormattedTextField c_celular;
    private javax.swing.JFormattedTextField c_cpf;
    private javax.swing.JTextField c_endBairro;
    private javax.swing.JFormattedTextField c_endCep;
    private javax.swing.JTextField c_endComp;
    private javax.swing.JTextField c_endNum;
    private javax.swing.JTextField c_endRua;
    private javax.swing.JTextField c_nome;
    private javax.swing.JFormattedTextField c_orcamento;
    private javax.swing.JTextField c_rg;
    private javax.swing.JComboBox<String> cbx_catPretendida;
    private javax.swing.JComboBox<String> cbx_formaPagamento;
    private com.toedter.calendar.JDateChooser dt_dataNasc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel l_cadCLiDataNasc;
    private javax.swing.JLabel l_cadCliCpf;
    private javax.swing.JLabel l_cadCliEnd1;
    private javax.swing.JLabel l_cadCliEnd2;
    private javax.swing.JLabel l_cadCliEnd3;
    private javax.swing.JLabel l_cadCliEnd4;
    private javax.swing.JLabel l_cadCliEnd5;
    private javax.swing.JLabel l_cadCliEnd6;
    private javax.swing.JLabel l_cadCliEnd7;
    private javax.swing.JLabel l_cadCliNome;
    private javax.swing.JLabel l_cadCliRg;
    private javax.swing.JLabel l_telefone;
    private javax.swing.JRadioButton r_feminino;
    private javax.swing.JRadioButton r_masculino;
    private javax.swing.JTabbedPane tab_cadastro;
    // End of variables declaration//GEN-END:variables
    ClienteCnh obj = new ClienteCnh();

    public void preencherCliente() {
        obj.setNome(c_nome.getText());
        obj.setCpf(c_cpf.getText());
        String cat = (String) cbx_catPretendida.getSelectedItem();
        obj.setCatPretendida(cat);
        if (cat.equals("Carro e Moto")) {
            obj.setQntAulasPossuidas(40);
        } else {
            obj.setQntAulasPossuidas(20);
        }
        obj.setCelular(c_celular.getText());
        obj.setDataNasc(dt_dataNasc.getDate());
        if (r_masculino.isSelected()) {
            obj.setSexo("MASCULINO");
        } else {
            obj.setSexo("FEMININO");
        }
        String auxOrc = c_orcamento.getText();
        auxOrc = auxOrc.replaceAll(",", ".");
        String fp = (String) cbx_formaPagamento.getSelectedItem();
        obj.setFormaPagamento(fp);
        double orc = Double.parseDouble(auxOrc);
        obj.setOrcamento(orc);

        obj.setEnd(""
                + c_endRua.getText().trim()
                + ", "
                + c_endNum.getText().trim()
                + ", Br."
                + c_endBairro.getText().trim()
                + ", "
                + c_endComp.getText().trim()
                + ", "
                + c_endCep.getText());
        obj.setRg(c_rg.getText());

    }

    public String endereco() {
        return (c_endRua.getText().trim() + ", " + c_endNum.getText().trim()
                + ", Br." + c_endBairro.getText().trim()
                + ", "
                + c_endComp.getText().trim()
                + ", "
                + c_endCep.getText());
    }

    public boolean verificaVazio() {
        return (c_nome.getText().trim().equals("") || endereco().equals(", , Br., CASA,   .   -   ")
                || dt_dataNasc == null || c_cpf.getText().equals("   .   .   -  ")
                || c_rg.getText().equals(""));
    }

}
