/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import Persistencia.IncluirEditarDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UnsupportedLookAndFeelException;
import Objetos.Instrutor;
import Objetos.Secretario;
import javax.swing.JOptionPane;

/**
 *
 * @author Pedrinho
 */
public class CadastroFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form CadastroCliente
     */
    public CadastroFuncionario() {
        initComponents();
        this.setLocationRelativeTo(null);
        tab_cadastro.setEnabled(false);
        bt_salvar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tab_cadastro = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        l_cadCliNome = new javax.swing.JLabel();
        c_nome = new javax.swing.JTextField();
        l_cadCLiDataNasc = new javax.swing.JLabel();
        l_cadCliRg = new javax.swing.JLabel();
        c_rg = new javax.swing.JTextField();
        l_cadCliCpf = new javax.swing.JLabel();
        l_telefone = new javax.swing.JLabel();
        c_celular = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        c_endRua = new javax.swing.JTextField();
        c_endBairro = new javax.swing.JTextField();
        c_endComp = new javax.swing.JTextField();
        l_cadCliEnd2 = new javax.swing.JLabel();
        l_cadCliEnd4 = new javax.swing.JLabel();
        l_cadCliEnd5 = new javax.swing.JLabel();
        l_cadCliEnd6 = new javax.swing.JLabel();
        l_cadCliEnd7 = new javax.swing.JLabel();
        c_endCep = new javax.swing.JFormattedTextField();
        c_endNum = new javax.swing.JFormattedTextField();
        l_cadCliEnd3 = new javax.swing.JLabel();
        dt_dataNasc = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        r_feminino = new javax.swing.JRadioButton();
        r_masculino = new javax.swing.JRadioButton();
        c_cpf = new javax.swing.JFormattedTextField();
        l_cadCLiDataNasc1 = new javax.swing.JLabel();
        dt_admissao = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        c_ctps = new javax.swing.JFormattedTextField();
        r_instrutor = new javax.swing.JRadioButton();
        r_secretario = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        dt_dataPCnh = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        c_credencial = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        r_null = new javax.swing.JRadioButton();
        r_ensino = new javax.swing.JRadioButton();
        r_geral = new javax.swing.JRadioButton();
        bt_proximo = new javax.swing.JButton();
        bt_anterior = new javax.swing.JButton();
        bt_salvar = new javax.swing.JButton();
        bt_sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Cadastro Funcionário");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 0, 170, 20);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(null);

        l_cadCliNome.setText("Nome");
        jPanel2.add(l_cadCliNome);
        l_cadCliNome.setBounds(20, 0, 70, 30);

        c_nome.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jPanel2.add(c_nome);
        c_nome.setBounds(20, 30, 290, 30);

        l_cadCLiDataNasc.setText("Data de Nasc.");
        l_cadCLiDataNasc.setToolTipText("Data de Nascimento");
        jPanel2.add(l_cadCLiDataNasc);
        l_cadCLiDataNasc.setBounds(180, 60, 80, 30);

        l_cadCliRg.setText("RG");
        jPanel2.add(l_cadCliRg);
        l_cadCliRg.setBounds(330, 0, 40, 30);

        c_rg.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jPanel2.add(c_rg);
        c_rg.setBounds(330, 30, 140, 30);

        l_cadCliCpf.setText("CPF");
        jPanel2.add(l_cadCliCpf);
        l_cadCliCpf.setBounds(20, 60, 40, 30);

        l_telefone.setText("Celular");
        jPanel2.add(l_telefone);
        l_telefone.setBounds(20, 280, 50, 30);

        try {
            c_celular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        c_celular.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jPanel2.add(c_celular);
        c_celular.setBounds(20, 310, 110, 30);

        jPanel3.setLayout(null);

        c_endRua.setToolTipText("");
        jPanel3.add(c_endRua);
        c_endRua.setBounds(10, 30, 190, 30);
        jPanel3.add(c_endBairro);
        c_endBairro.setBounds(290, 30, 130, 30);

        c_endComp.setText("CASA");
        c_endComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_endCompActionPerformed(evt);
            }
        });
        jPanel3.add(c_endComp);
        c_endComp.setBounds(10, 90, 140, 30);

        l_cadCliEnd2.setText("Bairro");
        jPanel3.add(l_cadCliEnd2);
        l_cadCliEnd2.setBounds(290, 0, 50, 30);

        l_cadCliEnd4.setText("Rua");
        jPanel3.add(l_cadCliEnd4);
        l_cadCliEnd4.setBounds(10, 0, 70, 30);

        l_cadCliEnd5.setText("Complemento");
        jPanel3.add(l_cadCliEnd5);
        l_cadCliEnd5.setBounds(10, 60, 90, 30);

        l_cadCliEnd6.setText("Num");
        jPanel3.add(l_cadCliEnd6);
        l_cadCliEnd6.setBounds(220, 0, 50, 30);

        l_cadCliEnd7.setText("CEP");
        jPanel3.add(l_cadCliEnd7);
        l_cadCliEnd7.setBounds(170, 60, 50, 30);

        try {
            c_endCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        c_endCep.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jPanel3.add(c_endCep);
        c_endCep.setBounds(170, 90, 120, 30);

        c_endNum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jPanel3.add(c_endNum);
        c_endNum.setBounds(210, 30, 70, 30);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(20, 150, 470, 130);

        l_cadCliEnd3.setText("Endereço");
        jPanel2.add(l_cadCliEnd3);
        l_cadCliEnd3.setBounds(20, 120, 70, 30);

        dt_dataNasc.setToolTipText("");
        dt_dataNasc.setDateFormatString("dd/MM/y");
        dt_dataNasc.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        dt_dataNasc.setMaxSelectableDate(new java.util.Date(7289578800000L));
        dt_dataNasc.setMinSelectableDate(new java.util.Date(-2208977612000L));
        jPanel2.add(dt_dataNasc);
        dt_dataNasc.setBounds(180, 90, 130, 30);

        jLabel4.setText("Sexo");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(330, 60, 60, 30);

        buttonGroup3.add(r_feminino);
        r_feminino.setSelected(true);
        r_feminino.setText("Feminino");
        jPanel2.add(r_feminino);
        r_feminino.setBounds(330, 90, 90, 30);

        buttonGroup3.add(r_masculino);
        r_masculino.setText("Masculino");
        jPanel2.add(r_masculino);
        r_masculino.setBounds(410, 90, 98, 30);

        try {
            c_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        c_cpf.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jPanel2.add(c_cpf);
        c_cpf.setBounds(20, 90, 140, 30);

        l_cadCLiDataNasc1.setText("Data de Amissão");
        jPanel2.add(l_cadCLiDataNasc1);
        l_cadCLiDataNasc1.setBounds(320, 280, 100, 30);

        dt_admissao.setToolTipText("");
        dt_admissao.setDateFormatString("dd/MM/y");
        dt_admissao.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        dt_admissao.setMaxSelectableDate(new java.util.Date(7289578800000L));
        dt_admissao.setMinSelectableDate(new java.util.Date(-2208977612000L));
        jPanel2.add(dt_admissao);
        dt_admissao.setBounds(320, 310, 130, 30);

        jLabel2.setText("CTPS");
        jLabel2.setToolTipText("Carteira de Trabalho e Previdência Social");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(150, 280, 60, 30);

        try {
            c_ctps.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(c_ctps);
        c_ctps.setBounds(150, 310, 150, 30);

        buttonGroup5.add(r_instrutor);
        r_instrutor.setSelected(true);
        r_instrutor.setText("Instrutor(a)");
        r_instrutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_instrutorActionPerformed(evt);
            }
        });
        jPanel2.add(r_instrutor);
        r_instrutor.setBounds(20, 370, 100, 30);

        buttonGroup5.add(r_secretario);
        r_secretario.setText("Secretário(a)");
        r_secretario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_secretarioActionPerformed(evt);
            }
        });
        jPanel2.add(r_secretario);
        r_secretario.setBounds(130, 370, 100, 30);

        tab_cadastro.addTab("Funcionário", jPanel2);

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));
        jPanel4.setLayout(null);

        jPanel6.setLayout(null);

        jLabel7.setText("Data Primeira Habilitação");
        jPanel6.add(jLabel7);
        jLabel7.setBounds(220, 20, 140, 30);

        dt_dataPCnh.setToolTipText("");
        dt_dataPCnh.setDateFormatString("dd/MM/y");
        dt_dataPCnh.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        dt_dataPCnh.setMaxSelectableDate(new java.util.Date(7289578800000L));
        dt_dataPCnh.setMinSelectableDate(new java.util.Date(-2208977612000L));
        jPanel6.add(dt_dataPCnh);
        dt_dataPCnh.setBounds(220, 50, 140, 30);

        jLabel3.setText("Credencial");
        jPanel6.add(jLabel3);
        jLabel3.setBounds(40, 20, 80, 30);

        try {
            c_credencial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("############")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        c_credencial.setToolTipText("Adicione 12 números");
        jPanel6.add(c_credencial);
        c_credencial.setBounds(40, 50, 150, 30);

        jLabel6.setText("Especialização");
        jPanel6.add(jLabel6);
        jLabel6.setBounds(40, 100, 140, 30);

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        buttonGroup6.add(r_null);
        r_null.setSelected(true);
        r_null.setText("Somente Instrutor");

        buttonGroup6.add(r_ensino);
        r_ensino.setText("Diretor de Ensino");

        buttonGroup6.add(r_geral);
        r_geral.setText("Diretor Geral");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r_null, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r_ensino, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r_geral, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(r_null, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(r_ensino, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(r_geral, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel6.add(jPanel5);
        jPanel5.setBounds(40, 130, 160, 102);

        jPanel4.add(jPanel6);
        jPanel6.setBounds(50, 60, 440, 270);

        tab_cadastro.addTab("Instrutor", jPanel4);

        jPanel1.add(tab_cadastro);
        tab_cadastro.setBounds(0, 20, 520, 450);

        bt_proximo.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        bt_proximo.setText("Próximo");
        bt_proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_proximoActionPerformed(evt);
            }
        });
        jPanel1.add(bt_proximo);
        bt_proximo.setBounds(190, 480, 80, 30);

        bt_anterior.setText("Anterior");
        bt_anterior.setEnabled(false);
        bt_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_anteriorActionPerformed(evt);
            }
        });
        jPanel1.add(bt_anterior);
        bt_anterior.setBounds(100, 480, 80, 30);

        bt_salvar.setText("Salvar");
        bt_salvar.setEnabled(false);
        bt_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salvarActionPerformed(evt);
            }
        });
        jPanel1.add(bt_salvar);
        bt_salvar.setBounds(10, 480, 80, 30);

        bt_sair.setText("Sair");
        bt_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_sairActionPerformed(evt);
            }
        });
        jPanel1.add(bt_sair);
        bt_sair.setBounds(430, 480, 80, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_anteriorActionPerformed
        // TODO add your handling code here:

        tab_cadastro.setSelectedIndex(0);
        bt_proximo.setEnabled(true);
        bt_anterior.setEnabled(false);
        bt_salvar.setEnabled(false);

    }//GEN-LAST:event_bt_anteriorActionPerformed

    private void bt_proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_proximoActionPerformed
        // TODO add your handling code here:
        if (!verificaVazio()) {
            tab_cadastro.setSelectedIndex(1);
            bt_salvar.setEnabled(true);
            bt_anterior.setEnabled(true);
            bt_proximo.setEnabled(false);
        } else {

            JOptionPane.showMessageDialog(null, "Preencha todos campos para prosseguir!", "Atenção", 0);
        }
    }//GEN-LAST:event_bt_proximoActionPerformed

    private void bt_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salvarActionPerformed
        // TODO add your handling code here:
        if (!verificaVazio()) {
            IncluirEditarDAO iedao = new IncluirEditarDAO();
            try {
                if (r_secretario.isSelected()) {

                    iedao.Incluir(preencherSecretario());

                } else {

                    iedao.Incluir(preencherInstrutor());
                }
                JOptionPane.showMessageDialog(null, "Salvo com sucesso!");
                this.dispose();
            } catch (SQLException ex) {
                Logger.getLogger(CadastroFuncionario.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Preencha todos campos para prosseguir!", "Atenção", 0);
        }

    }//GEN-LAST:event_bt_salvarActionPerformed

    private void c_endCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_endCompActionPerformed
        // TODO add your handling code here:
        c_endComp.setText("");
    }//GEN-LAST:event_c_endCompActionPerformed

    private void r_secretarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_secretarioActionPerformed
        // TODO add your handling code here:
        bt_salvar.setEnabled(true);
        bt_proximo.setEnabled(false);
    }//GEN-LAST:event_r_secretarioActionPerformed

    private void r_instrutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_instrutorActionPerformed
        // TODO add your handling code here:
        bt_salvar.setEnabled(false);
        bt_proximo.setEnabled(true);
    }//GEN-LAST:event_r_instrutorActionPerformed

    private void bt_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_sairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_bt_sairActionPerformed

    /**
     * @param args the command line arguments
     * @throws java.lang.ClassNotFoundException
     * @throws java.lang.InstantiationException
     * @throws java.lang.IllegalAccessException
     * @throws javax.swing.UnsupportedLookAndFeelException
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }

        }
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CadastroFuncionario().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_anterior;
    private javax.swing.JButton bt_proximo;
    private javax.swing.JButton bt_sair;
    private javax.swing.JButton bt_salvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.JFormattedTextField c_celular;
    private javax.swing.JFormattedTextField c_cpf;
    private javax.swing.JFormattedTextField c_credencial;
    private javax.swing.JFormattedTextField c_ctps;
    private javax.swing.JTextField c_endBairro;
    private javax.swing.JFormattedTextField c_endCep;
    private javax.swing.JTextField c_endComp;
    private javax.swing.JFormattedTextField c_endNum;
    private javax.swing.JTextField c_endRua;
    private javax.swing.JTextField c_nome;
    private javax.swing.JTextField c_rg;
    private com.toedter.calendar.JDateChooser dt_admissao;
    private com.toedter.calendar.JDateChooser dt_dataNasc;
    private com.toedter.calendar.JDateChooser dt_dataPCnh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel l_cadCLiDataNasc;
    private javax.swing.JLabel l_cadCLiDataNasc1;
    private javax.swing.JLabel l_cadCliCpf;
    private javax.swing.JLabel l_cadCliEnd2;
    private javax.swing.JLabel l_cadCliEnd3;
    private javax.swing.JLabel l_cadCliEnd4;
    private javax.swing.JLabel l_cadCliEnd5;
    private javax.swing.JLabel l_cadCliEnd6;
    private javax.swing.JLabel l_cadCliEnd7;
    private javax.swing.JLabel l_cadCliNome;
    private javax.swing.JLabel l_cadCliRg;
    private javax.swing.JLabel l_telefone;
    private javax.swing.JRadioButton r_ensino;
    private javax.swing.JRadioButton r_feminino;
    private javax.swing.JRadioButton r_geral;
    private javax.swing.JRadioButton r_instrutor;
    private javax.swing.JRadioButton r_masculino;
    private javax.swing.JRadioButton r_null;
    private javax.swing.JRadioButton r_secretario;
    private javax.swing.JTabbedPane tab_cadastro;
    // End of variables declaration//GEN-END:variables

    public Instrutor preencherInstrutor() {
        Instrutor obj = new Instrutor();
        obj.setNome(c_nome.getText());
        obj.setCpf(c_cpf.getText());
        obj.setCelular(c_celular.getText());
        obj.setDataNasc(dt_dataNasc.getDate());
        if (r_masculino.isSelected()) {
            obj.setSexo("MASCULINO");
        } else {
            obj.setSexo("FEMININO");
        }
        obj.setEnd(""
                + c_endRua.getText().trim()
                + ", "
                + c_endNum.getText().trim()
                + ", Br."
                + c_endBairro.getText().trim()
                + ", "
                + c_endComp.getText().trim()
                + ", "
                + c_endCep.getText());
        obj.setRg(c_rg.getText());
        obj.setCredencial(c_credencial.getText());
        obj.setDataPCnh(dt_dataPCnh.getDate());
        obj.setCtps(c_ctps.getText());
        obj.setDataAdmissao(dt_admissao.getDate());
        if (r_null.isSelected()) {
            obj.setDiretor("NÂO");
        } else if (r_geral.isSelected()) {
            obj.setDiretor("GERAL");
        } else {
            obj.setDiretor("Ensino");
        }
        return obj;
    }

    public Secretario preencherSecretario() {

        Secretario obj = new Secretario();
        obj.setNome(c_nome.getText());
        obj.setCpf(c_cpf.getText());
        obj.setCelular(c_celular.getText());
        obj.setDataNasc(dt_dataNasc.getDate());
        if (r_masculino.isSelected()) {
            obj.setSexo("MASCULINO");
        } else {
            obj.setSexo("FEMININO");
        }
        obj.setRg(c_rg.getText());
        obj.setEnd(""
                + c_endRua.getText().trim()
                + ", "
                + c_endNum.getText().trim()
                + ", Br."
                + c_endBairro.getText().trim()
                + ", "
                + c_endComp.getText().trim()
                + ", "
                + c_endCep.getText());
        obj.setCtps(c_ctps.getText());
        obj.setDataAdmissao(dt_admissao.getDate());
        return obj;
    }

    public String endereco() {
        return (c_endRua.getText().trim() + ", " + c_endNum.getText().trim()
                + ", Br." + c_endBairro.getText().trim()
                + ", "
                + c_endComp.getText().trim()
                + ", "
                + c_endCep.getText());
    }

    public boolean verificaVazio() {
        return (c_nome.getText().trim().equals("") || endereco().equals(", , Br., CASA,   .   -   ")
                || dt_dataNasc == null || c_cpf.getText().equals("   .   .   -  ")
                || c_rg.getText().equals("") || c_ctps.getText().equals(""));
    }

}
