/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

/**
 *
 * @author Pedrinho
 */
public class Config extends javax.swing.JFrame {

    /**
     * Creates new form Config
     */
    public Config() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextField24 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextField25 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextField28 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTextField29 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jTextField32 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jTextField26 = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jTextField27 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jTextField34 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jTextField35 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setText("Qnt aula Carro INI");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 10, 95, 16);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(30, 30, 116, 22);

        jLabel2.setText("Qnt aula Carro ADI");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 60, 99, 16);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(30, 80, 116, 22);

        jLabel3.setText("Qnt aula Moto INI");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 110, 95, 16);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(30, 130, 116, 22);

        jLabel4.setText("Qnt aula Moto ADI");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 160, 99, 16);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(30, 180, 116, 22);

        jLabel5.setText("Qnt aula Ônibus");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 210, 86, 16);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(30, 230, 116, 22);

        jLabel6.setText("Val aula Carro");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(160, 10, 73, 16);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(160, 30, 116, 22);

        jLabel19.setText("Aluguel Moto");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(160, 210, 73, 16);
        jPanel1.add(jTextField19);
        jTextField19.setBounds(160, 230, 116, 22);

        jLabel20.setText("Aluguel Ônibus");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(160, 260, 82, 16);
        jPanel1.add(jTextField20);
        jTextField20.setBounds(160, 280, 116, 22);

        jLabel21.setText("Salário Mínimo");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(160, 310, 80, 16);
        jPanel1.add(jTextField21);
        jTextField21.setBounds(160, 330, 116, 22);

        jLabel22.setText("Val aula Moto");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(160, 60, 73, 16);
        jPanel1.add(jTextField22);
        jTextField22.setBounds(160, 80, 116, 22);

        jLabel23.setText("Val aula ônibus");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(160, 110, 80, 16);

        jTextField23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField23ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField23);
        jTextField23.setBounds(160, 130, 116, 22);

        jLabel24.setText("Aluguel Carro");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(160, 160, 73, 16);
        jPanel1.add(jTextField24);
        jTextField24.setBounds(160, 180, 116, 22);

        jLabel25.setText(":");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(340, 180, 20, 16);
        jPanel1.add(jTextField25);
        jTextField25.setBounds(350, 180, 40, 22);

        jLabel26.setText("Hora de fechamento");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(290, 210, 109, 16);

        jLabel27.setText("Hora inicio almoço");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(290, 260, 120, 16);

        jLabel28.setText("Sal. Diretor de Ensino");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(290, 10, 111, 16);
        jPanel1.add(jTextField28);
        jTextField28.setBounds(290, 30, 116, 22);

        jLabel29.setText("Sal. Diretor geral");
        jPanel1.add(jLabel29);
        jLabel29.setBounds(290, 60, 86, 16);

        jTextField29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField29ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField29);
        jTextField29.setBounds(290, 80, 116, 22);

        jLabel30.setText("Valor Aula Dada");
        jPanel1.add(jLabel30);
        jLabel30.setBounds(290, 110, 84, 16);
        jPanel1.add(jTextField30);
        jTextField30.setBounds(290, 130, 116, 22);
        jPanel1.add(jTextField31);
        jTextField31.setBounds(290, 180, 40, 22);

        jLabel31.setText("Hora de abertura");
        jPanel1.add(jLabel31);
        jLabel31.setBounds(290, 160, 89, 16);
        jPanel1.add(jTextField32);
        jTextField32.setBounds(290, 230, 40, 22);

        jLabel32.setText(":");
        jPanel1.add(jLabel32);
        jLabel32.setBounds(340, 230, 20, 16);
        jPanel1.add(jTextField26);
        jTextField26.setBounds(350, 230, 40, 22);
        jPanel1.add(jTextField33);
        jTextField33.setBounds(290, 280, 40, 22);

        jLabel33.setText(":");
        jPanel1.add(jLabel33);
        jLabel33.setBounds(340, 280, 20, 16);
        jPanel1.add(jTextField27);
        jTextField27.setBounds(350, 280, 40, 22);

        jLabel34.setText("Hora fim almoço");
        jPanel1.add(jLabel34);
        jLabel34.setBounds(290, 310, 120, 16);
        jPanel1.add(jTextField34);
        jTextField34.setBounds(290, 330, 40, 22);

        jLabel35.setText(":");
        jPanel1.add(jLabel35);
        jLabel35.setBounds(340, 330, 20, 16);
        jPanel1.add(jTextField35);
        jTextField35.setBounds(350, 330, 40, 22);

        jButton1.setText("Salvar");
        jPanel1.add(jButton1);
        jButton1.setBounds(520, 20, 70, 23);

        jToggleButton1.setText("Editar");
        jPanel1.add(jToggleButton1);
        jToggleButton1.setBounds(520, 60, 70, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField23ActionPerformed

    private void jTextField29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField29ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Config().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
