/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import Objetos.Instrutor;
import Objetos.Secretario;
import Persistencia.ConsultaDAO;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pedrinho
 */
public class GeraSalario extends javax.swing.JFrame {

    /**
     * Creates new form GeraSalario
     */
    public GeraSalario() {
        initComponents();
        atualizarTabFuncionario();
        this.setLocationRelativeTo(null);
        this.setExtendedState(GeraSalario.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        tb_funcionario = new javax.swing.JTable();
        bt_atualizarInstrutor = new javax.swing.JButton();
        bt_sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        tb_funcionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "CPF", "Salario", "Aulas Dadas", "Diretor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_funcionario.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tb_funcionario.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane11.setViewportView(tb_funcionario);

        jPanel1.add(jScrollPane11);
        jScrollPane11.setBounds(10, 10, 1160, 590);

        bt_atualizarInstrutor.setText("Atualizar");
        bt_atualizarInstrutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_atualizarInstrutorActionPerformed(evt);
            }
        });
        jPanel1.add(bt_atualizarInstrutor);
        bt_atualizarInstrutor.setBounds(1200, 10, 90, 30);

        bt_sair.setText("Sair");
        bt_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_sairActionPerformed(evt);
            }
        });
        jPanel1.add(bt_sair);
        bt_sair.setBounds(1200, 50, 90, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1322, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_atualizarInstrutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_atualizarInstrutorActionPerformed
        // TODO add your handling code here:
        atualizarTabFuncionario();
    }//GEN-LAST:event_bt_atualizarInstrutorActionPerformed

    private void bt_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_sairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_bt_sairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GeraSalario().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_atualizarInstrutor;
    private javax.swing.JButton bt_sair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JTable tb_funcionario;
    // End of variables declaration//GEN-END:variables

    ArrayList<Secretario> listSec = new ArrayList();
    ArrayList<Instrutor> listInst = new ArrayList();

    public void atualizarTabFuncionario() {
        DefaultTableModel mp1 = (DefaultTableModel) tb_funcionario.getModel();
        int l = mp1.getRowCount();
        if (l > 0) {
            while (l > 0) {
                ((DefaultTableModel) tb_funcionario.getModel()).removeRow(l - 1);
                l--;
            }
        }
        try {
            ResultSet rs = ConsultaDAO.carregaInstrutor();
            DefaultTableModel mp = (DefaultTableModel) tb_funcionario.getModel();
            while (rs.next()) {
                Instrutor inst = new Instrutor();
                String Coluna1 = rs.getString("nome").trim();
                String Coluna2 = rs.getString("cpf").trim();
                int Coluna4 = rs.getInt("aulasdadas");
                String Coluna5 = rs.getString("diretor").trim();
                inst.setNome(Coluna1);
                inst.setCpf(Coluna2);
                inst.setDiretor(Coluna5);
                inst.setAulasDadas(Coluna4);
                inst.setSalario();
                Double Coluna3 = inst.getSalario();
                listInst.add(inst);
                mp.addRow(new String[]{Coluna1, Coluna2, Coluna3 + "0", Coluna4 + "", Coluna5});
            }
            ResultSet re = ConsultaDAO.carregaSecretario();
            while (re.next()) {
                Secretario sec = new Secretario();
                String Coluna1 = re.getString("nome").trim();
                String Coluna2 = re.getString("cpf").trim();
                Double Coluna3 = re.getDouble("salario");
                listSec.add(sec);
                mp.addRow(new String[]{Coluna1, Coluna2, Coluna3 + "0", "null", "null"});
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Solicitação interrompida: " + e, "Preencher item", 2);
        }

        tb_funcionario.setAutoCreateRowSorter(true);
    }
}
