/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import static CodigosAuxiliares.GeraListas.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Pedrinho
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menuzin
     */
    public Menu() {
        try {
            initComponents();
            geraListaCli();
            geraListaInst();
            geraListaVei();
            geraListaAula();
            geraListaHorario();
            this.setLocationRelativeTo(null);
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        painel = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        br_marcaAula = new javax.swing.JButton();
        bt_geraSalario = new javax.swing.JButton();
        bt_quadro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bt_consulta = new javax.swing.JButton();
        bt_sair = new javax.swing.JButton();
        bt_cadastroCliente = new javax.swing.JButton();
        bt_cadastroFuncionario = new javax.swing.JButton();
        bt_cadastroVeiculo = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        br_marcaAula.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        br_marcaAula.setText("Marcar aula");
        br_marcaAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                br_marcaAulaActionPerformed(evt);
            }
        });
        jPanel1.add(br_marcaAula);
        br_marcaAula.setBounds(100, 180, 190, 50);

        bt_geraSalario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_geraSalario.setText("Gerar salário");
        bt_geraSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_geraSalarioActionPerformed(evt);
            }
        });
        jPanel1.add(bt_geraSalario);
        bt_geraSalario.setBounds(100, 240, 190, 50);

        bt_quadro.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        bt_quadro.setText("Quadro de horário");
        bt_quadro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_quadroActionPerformed(evt);
            }
        });
        jPanel1.add(bt_quadro);
        bt_quadro.setBounds(100, 120, 190, 50);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setText("Bem-Vindo ao Menu Principal");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(100, 30, 430, 70);

        bt_consulta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_consulta.setText("Gerência");
        bt_consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_consultaActionPerformed(evt);
            }
        });
        jPanel1.add(bt_consulta);
        bt_consulta.setBounds(150, 300, 300, 50);

        bt_sair.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bt_sair.setText("Sair");
        bt_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_sairActionPerformed(evt);
            }
        });
        jPanel1.add(bt_sair);
        bt_sair.setBounds(530, 350, 90, 40);

        bt_cadastroCliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_cadastroCliente.setText("Cadastro Cliente");
        bt_cadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cadastroClienteActionPerformed(evt);
            }
        });
        jPanel1.add(bt_cadastroCliente);
        bt_cadastroCliente.setBounds(310, 120, 190, 50);

        bt_cadastroFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_cadastroFuncionario.setText("Cadastro Funcionário");
        bt_cadastroFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cadastroFuncionarioActionPerformed(evt);
            }
        });
        jPanel1.add(bt_cadastroFuncionario);
        bt_cadastroFuncionario.setBounds(310, 180, 190, 50);

        bt_cadastroVeiculo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_cadastroVeiculo.setText("Cadastro Veículo");
        bt_cadastroVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cadastroVeiculoActionPerformed(evt);
            }
        });
        jPanel1.add(bt_cadastroVeiculo);
        bt_cadastroVeiculo.setBounds(310, 240, 190, 50);

        painel.add(jPanel1);
        jPanel1.setBounds(50, 40, 630, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_quadroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_quadroActionPerformed

        Quadro quadro = new Quadro();
        quadro.setVisible(true);
    }//GEN-LAST:event_bt_quadroActionPerformed

    private void br_marcaAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_br_marcaAulaActionPerformed
        try {
            // TODO add your handling code here:
            MarcarAula cadastroAula = new MarcarAula();
            cadastroAula.setVisible(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_br_marcaAulaActionPerformed

    private void bt_consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_consultaActionPerformed
        try {
            // TODO add your handling code here:
            Consulta consulta = new Consulta(0);
            consulta.setVisible(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_bt_consultaActionPerformed

    private void bt_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_sairActionPerformed
        // TODO add your handling code here:
        if (0 == JOptionPane.showConfirmDialog(null, "Deseja sair?", "Confirmação", JOptionPane.YES_NO_OPTION)) {
            System.exit(0);
        }

    }//GEN-LAST:event_bt_sairActionPerformed

    private void bt_cadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cadastroClienteActionPerformed
        // TODO add your handling code here:
        CadastroClienteCNH cadastroCliente = new CadastroClienteCNH();
        cadastroCliente.setVisible(true);
    }//GEN-LAST:event_bt_cadastroClienteActionPerformed

    private void bt_cadastroFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cadastroFuncionarioActionPerformed
        // TODO add your handling code here:
        CadastroFuncionario cadFunc = new CadastroFuncionario();
        cadFunc.setVisible(true);
    }//GEN-LAST:event_bt_cadastroFuncionarioActionPerformed

    private void bt_cadastroVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cadastroVeiculoActionPerformed
        // TODO add your handling code here:
        CadastroVeiculo cadVei = new CadastroVeiculo();
        cadVei.setVisible(true);
    }//GEN-LAST:event_bt_cadastroVeiculoActionPerformed

    private void bt_geraSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_geraSalarioActionPerformed
        // TODO add your handling code here:
        GeraSalario gs = new GeraSalario();
        gs.setVisible(true);
    }//GEN-LAST:event_bt_geraSalarioActionPerformed

    /**
     * @param args the command line arguments
     * @throws java.lang.ClassNotFoundException
     * @throws java.lang.InstantiationException
     * @throws java.lang.IllegalAccessException
     * @throws javax.swing.UnsupportedLookAndFeelException
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Menu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton br_marcaAula;
    private javax.swing.JButton bt_cadastroCliente;
    private javax.swing.JButton bt_cadastroFuncionario;
    private javax.swing.JButton bt_cadastroVeiculo;
    private javax.swing.JButton bt_consulta;
    private javax.swing.JButton bt_geraSalario;
    private javax.swing.JButton bt_quadro;
    private javax.swing.JButton bt_sair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JDesktopPane painel;
    // End of variables declaration//GEN-END:variables
}
